Adding counter contract with access control
KaizeNodeLabs/stark-cairo-nodes pull request #42
Opened 2024-11-22 20:23 UTC by Gerson2102

## Issue that Solves:
Solves #28 

## Main changes:

This PR is adding a simple counter contract with some access control. Only owner can call certain functions. And I added some additional functionalities related to addresses because are part of the workflow with addresses.

## Screenshot of behaviour:

Everything is working on my side:

![image](https://github.com/user-attachments/assets/8964d126-8fbc-47a8-92ea-15bbe6336736)

2024-11-23 10:10 UTC, danielcdz commented
@Gerson2102 this looks good overall but please move it to the contract directory inside `/starknet`

2024-11-23 16:34 UTC, Gerson2102 commented
Got it. I think I addressed all the feedback now.

2024-11-24 04:36 UTC, danielcdz requested changes

2024-11-24 04:36 UTC, danielcdz commented on cairo/scripts/.tool-versions
this is not needed

2024-11-24 04:36 UTC, danielcdz commented on cairo/scripts/hello_world/.tool-versions
can you remove all changes from this directory please

2024-11-24 17:04 UTC, Gerson2102 commented on cairo/scripts/hello_world/.tool-versions
Which changes? Deleting `.tool-versions` and `Scarb.lock`?

2024-11-24 17:05 UTC, Gerson2102 commented on cairo/scripts/hello_world/.tool-versions
Or deleting just the contents of `.tool-versions`?

2024-11-24 21:40 UTC, danielcdz commented on cairo/scripts/hello_world/.tool-versions
you have changes in cairo/scripts/hello_world that are not needed, don't include those changes in this PR

2024-11-24 21:51 UTC, Gerson2102 commented on cairo/scripts/hello_world/.tool-versions
I deleted the versions file and the changes in the scarb lock.

2024-11-24 21:52 UTC, danielcdz approved these changes

2024-11-24 22:05 UTC, merged