Issue #59: Implement script/contract for random number generator
KaizeNodeLabs/stark-cairo-nodes pull request #78
Opened 2024-12-14 13:10 UTC by jorgezerpa

Create a contract RandomNumberGeneratorContract and it's tests. 

The contract has 4 examples of how to generate random numbers:
- get_random_number_with_block_data
- get_random_number_with_keccak256
- get_random_number_with_user_entropy
- get_random_number_with_vrf & receive_random_words 

The first 3 methods has an input that applies a bit of entropy to "ensure" randomness but are not recommended since such randomness is not verifiable. 
The last method uses the Pragma VRF functionality to get the number. the get_random_number_with_vrf request a random number and the receive_random_words is the function used as callback by the VRF contract to return the random number. 

I'm attentive to any correction/question🚀🚀

2024-12-19 15:21 UTC, coxmars reviewed
@jorgezerpa add a .tools-versions file in the project "starknet/contracts/random_number_generator" to document your dependencies.

2024-12-19 15:24 UTC, coxmars commented
@jorgezerpa please send an image of your tests results to validate all of them are passing and it is working as expected 🫡

2024-12-19 15:27 UTC, jorgezerpa commented
@coxmars Hello! I do it super fast🏃🏃

2024-12-19 15:34 UTC, jorgezerpa commented
.tools-versions file added.
Here's the image:  of tests: 
![image](https://github.com/user-attachments/assets/e8294e5a-1f42-406d-816e-bf378b953e5e)

2024-12-19 15:35 UTC, coxmars commented
> .tools-versions file added. Here's the image: of tests: ![image](https://private-user-images.githubusercontent.com/90111873/397434264-e8294e5a-1f42-406d-816e-bf378b953e5e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ2MjI4MTQsIm5iZiI6MTczNDYyMjUxNCwicGF0aCI6Ii85MDExMTg3My8zOTc0MzQyNjQtZTgyOTRlNWEtMWY0Mi00MDZkLTgxNmUtYmYzNzhiOTUzZTVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE5VDE1MzUxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE5NDFhNGQ4ZmVkYTQzNmQxMDllMWZmYTVjZTA0ZmY5NTdmODBjMTk3MGNhZTM2N2E3YzA4NWY3YmI0Mjg1YzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.hkw7RwJyxj-R1pZ6t-q2oA_yEqJJtuy5CTjowrhAFz4)

Awesome job sir, I will review it 🫡

2024-12-20 15:52 UTC, danielcdz requested changes

2024-12-20 15:52 UTC, danielcdz commented on starknet/contracts/random_number_generator/ .tools-versions
this file needs to be named .tool-versions to work properly, can you please rename it?

2024-12-20 16:14 UTC, jorgezerpa commented
@danielcdz Ready both changes sir!

2024-12-20 16:22 UTC, danielcdz commented on starknet/contracts/random_number_generator/.tool-versions
this file needs an extra line at the end, then we can merge! 🚀

2024-12-20 18:12 UTC, jorgezerpa commented on starknet/contracts/random_number_generator/.tool-versions
Done this here🥷

2024-12-20 22:17 UTC, danielcdz approved these changes

2024-12-20 22:17 UTC, merged