complete feat/stack_data_structure
KaizeNodeLabs/stark-cairo-nodes pull request #79
Opened 2024-12-14 19:19 UTC by KevinMB0220

# 🛠️ Implementation of `MemoryVec` in Cairo

## Description
A `MemoryVec` structure has been implemented in Cairo to efficiently manage in-memory vectors. This structure uses a `Felt252Dict` with `Nullable` elements to store data and provides methods that replicate typical vector functionalities, such as adding, accessing, and removing elements.

## Key Features
- **Initialization**: `new` method to create an empty vector.
- **Access**:
  - `get`: Returns an optional element by index.
  - `at`: Returns an element directly; throws an error if the index is out of bounds.
- **Modification**:
  - `push`: Adds an element to the end of the vector.
  - `set`: Updates the value at a specific position.
  - `pop`: Removes and returns the last element.
  - `peek`: Returns the last element without removing it.
- **Properties**:
  - `len`: Returns the current length of the vector.
  - `is_empty`: Checks if the vector is empty.
- **Destruction**: `Destruct` implementation ensures proper resource release by "squashing" the data.

## Use of Traits
The implementation uses the following traits:
- `MemoryVecTrait`: Defines the main operations for the vector.
- `NullableTrait`: Handles null values within the dictionary.
- `WrappingAdd`: Ensures safe length increments without overflow.

2024-12-19 15:18 UTC, coxmars reviewed
@KevinMB0220 add a .tools-versions file in the scarb project "cairo/scripts/stack_data_structure" to document your scarb version or other dependencies.

2024-12-19 18:53 UTC, coxmars commented
@KevinMB0220 can you add a small example using this data structure? It's to validate the functionality and provide a brief context for new devs who want to use it.

2024-12-20 00:21 UTC, KevinMB0220 commented
> @KevinMB0220 can you add a small example using this data structure? It's to validate the functionality and provide a brief context for new devs who want to use it.

Ready

2024-12-20 00:50 UTC, KevinMB0220 commented
> @KevinMB0220 can you add a small example using this data structure? It's to validate the functionality and provide a brief context for new devs who want to use it.

ready

2024-12-20 15:50 UTC, danielcdz requested changes

2024-12-20 15:50 UTC, danielcdz commented on cairo/scripts/stack_data_structure/.tools-versions
this file needs to be named:`.tool-versions` to works as expected

2024-12-20 15:51 UTC, danielcdz reviewed
Some files need an extra line at the end, can you please add it?

2024-12-20 16:04 UTC, KevinMB0220 commented
> Some files need an extra line at the end, can you please add it?

Ready

2024-12-20 16:05 UTC, KevinMB0220 commented on cairo/scripts/stack_data_structure/.tools-versions
Ready

2024-12-20 22:15 UTC, danielcdz approved these changes

2024-12-20 22:16 UTC, merged