Create template for PRs in .github directory #7
KaizeNodeLabs/stark-cairo-nodes pull request #9
Opened 2024-10-14 22:44 UTC by MariangelaNM

# 📝 Create template for PRs in .github directory #7

## 📖 Description
This pull request introduces a standardized template for all future pull requests in the repository. The template aims to improve the clarity and consistency of PR submissions, making it easier for reviewers to understand the changes proposed and the reasoning behind them.

### ❓ What does this PR do?
- Creates a pull request template in markdown format.
- Guides contributors on the necessary information to include when submitting a PR.

### 🚀 Why is this change necessary?
- Ensures that all PRs contain essential details, reducing back-and-forth communication.
- Helps maintain quality and consistency across submissions, making the review process smoother.

## ✅ Checklist
Please ensure your PR meets the following criteria before submission:

- [x] The code follows the project's coding standards and style guidelines.
- [x] I have tested the changes locally and they work as expected.
- [x] I have added/updated the necessary documentation (if applicable).
- [x] I have updated any relevant tests and they are passing.
- [x] This PR does not include any commented-out code or debug statements.

## 🔍 Changes Made
- Created a new directory `.github/PULL_REQUEST_TEMPLATE`.
- Added a markdown file `template.md` for the PR template.
- Included sections for description, checklist, changes made, related issues, screenshots, and additional notes.

## 🔗 Related Issues
- [issue 7](https://github.com/KaizeNodeLabs/stark-cairo-nodes/issues/7)

2024-10-14 22:45 UTC, MariangelaNM commented
@danielcdz

2024-10-15 22:34 UTC, danielcdz requested changes

2024-10-15 22:34 UTC, danielcdz commented on .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
> +## ✅ Checklist
This section can be avoided/deleted

2024-10-15 22:34 UTC, danielcdz commented on .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
> +### 🚀 Why is this change necessary?
This section can be deleted also

2024-10-15 22:34 UTC, danielcdz commented on .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
> +Please provide a clear and concise description of your changes. Include any relevant background information or context that may help reviewers understand the purpose of this PR.
Change this to: 
Please provide a general description of your changes. Include any relevant background information or context that may help reviewers understand the purpose of this PR.

2024-10-15 22:34 UTC, danielcdz commented on .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
> +- Related to #ISSUE_NUMBER
This can be deleted

2024-10-15 22:34 UTC, danielcdz commented
@MariangelaNM Thank you! I left some comments

2024-10-17 14:31 UTC, danielcdz commented
@MariangelaNM can you left the template with the sections I added to the description of this PR?

2024-10-20 00:15 UTC, MariangelaNM commented
# 📝 Create template for PRs in .github directory #7

## 📖 Description
This pull request introduces a standardized template for all future pull requests in the repository. The template aims to improve the clarity and consistency of PR submissions, making it easier for reviewers to understand the changes proposed and the reasoning behind them.

## 📸 Screenshots (if applicable)
-

## 📝 Additional Notes
- Add any relevant note that can enrich the description of the PR.

2024-10-20 00:17 UTC, MariangelaNM commented
@danielcdz  See how the implementation would be

2024-10-20 03:08 UTC, danielcdz reviewed
LGTM

2024-10-20 03:09 UTC, danielcdz approved these changes

2024-10-20 03:09 UTC, merged